# These are supported funding model platforms

github: []  # No GitHub Sponsors username provided
patreon: arvindranga69
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: arvindrangv
thanks_dev:
custom: ["https://paypal.me/arvindranga69"]
